### ISSUE TITLE
m-frame show/hide based on Distance to player

### ISSUE THREAD

**Issue by MetaZoneio** [mml-io/mml#149]
### What is your suggestion?

Currently when a scene is running many MML documents they will be via m-frames. So if the player is too far away from a specific m-frame it should automatically unload or hide the content. Once the player moves back to the valid distance the content should reappear. 

### Why is it important?

This will improve client side frame rate as content that isn't currently relevant to the player is hidden.

### How would you implement it?

`<m-frame distance="30">` or `<m-frame dist="30">` where distance attribute is in meters from the player to center of the MML content. So visible within the 30 meters specified, invisible when the player is outside the 30 meter range.

**Comment by MarcusLongmuir** [comment]
I've just [raised a PR](#155) that adds this functionality. Would be great to get your feedback on it, @MetaZoneio!

**Comment by MarcusLongmuir** [comment]
Resolved by #155
