### ISSUE TITLE
Standalone MML Viewer

### ISSUE THREAD

**Issue by MarcusLongmuir** [mml-io/mml#192]
There should be a "standalone" MML viewer that:
* Is hosted similar to the avatar tools web app on Github pages (no server component necessary)
* Allows specifying a query parameter to a websocket url that the viewer should show
* Allows specifying a "no-ui" parameter that allows the viewer to be embedded without any buttons showing over the content
* Has UI for picking lighting and environment maps (that are then reflected in the address)

This is conceptually a development from and on top of the current `mml-web-client` implementation in the repo: https://github.com/mml-io/mml/blob/9a392b1d1fb2a5be1bda39634c9fccd93932c434/packages/mml-web-client/src/index.ts#L44

**Comment by DirectiveCreator** [comment]
This would be amazing, as it makes it easier to embed an MML example for download as well, right now I have to use a mix of the link and Spline to display the model, a standalone MML viewer would be a lot nicer :)
